// Code generated by mockery v2.43.0. DO NOT EDIT.

package network

import (
	model "github.com/danesparza/iot-wifi-setup/internal/network/model"
	mock "github.com/stretchr/testify/mock"
)

// MockNetworkManagerService is an autogenerated mock type for the NetworkManagerService type
type MockNetworkManagerService struct {
	mock.Mock
}

type MockNetworkManagerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNetworkManagerService) EXPECT() *MockNetworkManagerService_Expecter {
	return &MockNetworkManagerService_Expecter{mock: &_m.Mock}
}

// ListAccessPoints provides a mock function with given fields:
func (_m *MockNetworkManagerService) ListAccessPoints() ([]model.AccessPoint, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListAccessPoints")
	}

	var r0 []model.AccessPoint
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]model.AccessPoint, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []model.AccessPoint); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AccessPoint)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNetworkManagerService_ListAccessPoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccessPoints'
type MockNetworkManagerService_ListAccessPoints_Call struct {
	*mock.Call
}

// ListAccessPoints is a helper method to define mock.On call
func (_e *MockNetworkManagerService_Expecter) ListAccessPoints() *MockNetworkManagerService_ListAccessPoints_Call {
	return &MockNetworkManagerService_ListAccessPoints_Call{Call: _e.mock.On("ListAccessPoints")}
}

func (_c *MockNetworkManagerService_ListAccessPoints_Call) Run(run func()) *MockNetworkManagerService_ListAccessPoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNetworkManagerService_ListAccessPoints_Call) Return(_a0 []model.AccessPoint, _a1 error) *MockNetworkManagerService_ListAccessPoints_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNetworkManagerService_ListAccessPoints_Call) RunAndReturn(run func() ([]model.AccessPoint, error)) *MockNetworkManagerService_ListAccessPoints_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNetworkManagerService creates a new instance of MockNetworkManagerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNetworkManagerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNetworkManagerService {
	mock := &MockNetworkManagerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
